layout_spectrum: 0.04601190644187281
typography_spectrum: 0.9953939675949145
color:
  lightness: 0.9660936851786578
  brandColors:
    - '#FFFFFF'
    - '#EDCB2F'
    - '#305A88'
    - '#DDDDDD'
    - '#4A6E97'
  saturation: 0.9772098394053629
  brandStrength: 0.5981915159797351
  rhythmicContrast: 0.137425425887698
content_rating:
  adult: false
github: true
opengraph: {}
analytics: {}
author:
  name: Filip Zajac
  url: filipzajac.me
  email: hi@filipzajac.me
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/22790db3-8a0e-4ab4-bee2-05703c581c66.svg
name: Filip Zajac
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Case Studies
    id: e6fcadac-df75-412a-b7e0-978b8b6db34f
    type: content
  - name: UI Design
    id: f0853ee7-3be7-43f8-9d98-e8583d87ff73
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e0facdb7-098c-409e-b6bc-d22bb06cb69d.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Design the future with me
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F127029158&url=https%3A%2F%2Fvimeo.com%2F127029158&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F604528720_1280.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=vimeo"
      width="1000" height="563" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://vimeo.com/xyzajac/lettering'
      keywords: []
      related: []
      author:
        - name: Filip Zajac
          url: 'https://vimeo.com/xyzajac'
          avatar: {}
      '@context': 'http://schema.org'
      title: Vectorize hand lettering with letterinkapp
      '@type': VideoObject
      app_links:
        - app_name: Vimeo
          namespace: ai
          app_store_id: '425194759'
          url: 'vimeo://app.vimeo.com/videos/127029158'
          type: ios
        - package: com.vimeo.android.videoapp
          app_name: Vimeo
          namespace: ai
          should_fallback: 'true'
          url: 'vimeo://app.vimeo.com/videos/127029158'
          type: web
        - id: '425194759'
          namespace: twitter
          url: 'vimeo://app.vimeo.com/videos/127029158'
          type: ipad
          name: Vimeo
        - id: '425194759'
          namespace: twitter
          url: 'vimeo://app.vimeo.com/videos/127029158'
          type: iphone
          name: Vimeo
        - id: com.vimeo.android.videoapp
          namespace: twitter
          url: 'vimeo://app.vimeo.com/videos/127029158'
          type: googleplay
          name: Vimeo
      publisher:
        favicon: 'https://f.vimeocdn.com/images_v6/favicon.ico'
        url: 'https://vimeo.com/'
        name: Vimeo
        domain: vimeo.com
      description: >-
        Create vectorized hand letterings in few minutes. Just skip unnecessary
        sketching and plotting curves in a computer. Letterink does it for you.
        Learn calligraphy Explore basics of calligraphy and create beautiful
        scripts step by step. Simulation of pointed nib helps you understand the
        fundamentals of calligraphy and create beautiful scripts.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Product designer '
purpose:
  - type: contact
    url: 'mailto:hi@filipzajac.me'
    label: Contact me
  - type: internal
    label: Meet me
    item: 8de6405a-f70c-4154-945c-fccc094a9d8e
