name: Filip Zajac
favicon: null
layout_spectrum: 0.5670688175596297
typography_spectrum: 0.11259541404433548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5993289386387914
  lightness: 0.39585428312420845
  saturation: 0.41548937768675387
  rhythmicContrast: 0.2050507478415966
purpose: []
